### ISSUE TITLE
Test fixes

### ISSUE THREAD

**Issue by luke-** [humhub/translation#47]

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/translation/pull/48, but I cannot understand why the test https://github.com/humhub/translation/runs/2800066045?check_suite_focus=true#step:23:34 is broken when on my side it works correctly:

![tests](https://user-images.githubusercontent.com/6995524/121642283-fdfd2e80-ca98-11eb-82da-bb24d75d2c2c.png)

**Comment by luke-** [comment]
That's strange. I can't reproduce it locally at the moment either. I have therefore temporarily commented out the test.
