### ISSUE TITLE
JA - Translate Issue

### ISSUE THREAD

**Issue by luke-** [humhub/translation#67]
Related: https://translate.humhub.org/s/ja/?contentId=96199&commentId=1177

**Comment by yurabakhtin** [comment]
@luke- 

> Problem 1

It was fixed and merged here https://github.com/humhub/translator/issues/48.

> Problem 2

It should be fixed by the old PR https://github.com/humhub/translation/pull/42, it was not merged, also I see the module has no releases and it seems the [CHANGELOG.md](https://github.com/humhub/translation/blob/b1fde90daa74411e6889e4aa8e029c8b4f0653c5/docs/CHANGELOG.md) file should be updated to keep only version `1.0.1` if it was not released or keep only `1.0.2` to void some errors on updating.

Please wait the merging until I will fix the tests there.

I confirm the problem 2 exists on `master` because the module "Custom Pages" has the folder name as `custom-pages` but id as `custom_pages`, so the translation module cannot find the message files.
It works well on the PR #42:
![fixed-translation](https://github.com/user-attachments/assets/07ece21b-7e7b-426f-b3da-b820bc80f48a)

**Comment by luke-** [comment]
@yurabakhtin Doh, I just merged it ;-)

**Comment by luke-** [comment]
*Thought the error was related to an old base

**Comment by yurabakhtin** [comment]
@luke- 

> *Thought the error was related to an old base

The error was in the new code from the merged PR #42, please merge new fix https://github.com/humhub/translation/pull/68.

**Comment by luke-** [comment]
Ok, just merged #68 and applied on the translation site.

Can you confirm the issue is fixed?

**Comment by yurabakhtin** [comment]
@luke- 

> Can you confirm the issue is fixed?

Yes, I confirm that I could reproduce the bug on `master` before, and then after applying the fix PR #42 I see it works as my screenshot above.

I forgot to inform that I have detected 3 modules which has the char `-` in folder name but `_` in module id:

- id = `custom_pages`, folder = `custom-pages`
- id = `advanced_search`, fodler = `advanced-search` (this module doesn't have the folde `messages`)
- id = `external_users`, folder = `external-users` (this module doesn't have the folde `messages`)

also one module `external_calendar` has `_` in id and in folder name.

Probably they all should be renamed to `-` for id and folder to avoid such conflicts in future.

**Comment by luke-** [comment]
@yurabakhtin Thanks.

Good point. I've created an issue here: https://github.com/humhub/humhub-internal/issues/359  - But it has no prio at the moment.
