### ISSUE TITLE
The Search field doesn't work any more on https://translate.humhub.org/

### ISSUE THREAD

**Issue by marc-farre** [humhub/translation#72]
![image](https://github.com/user-attachments/assets/d138aa63-30f8-463b-ac07-54e27664851e)

Might be related to https://github.com/humhub/translation/issues/71

**Comment by yurabakhtin** [comment]
@luke- @marc-farre Sorry, by mistake from the PR https://github.com/humhub/translation/pull/69/files#diff-15a982f497d86760b9b3c5d358eb9dfbcdb75f9e616ac1190071d2d7b92aca4aR108 where I have changed the html structure a little.
Fixed in the PR https://github.com/humhub/translation/pull/73.
Yes, the #71 is related and it has been fixed too.
